//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DllUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DllUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Check all or release all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonChekAllToolTip {
            get {
                return ResourceManager.GetString("ButtonChekAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download newer version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonDownloadToolTip {
            get {
                return ResourceManager.GetString("ButtonDownloadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace the checked dll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonReplaceToolTip {
            get {
                return ResourceManager.GetString("ButtonReplaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search for dll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSearchToolTip {
            get {
                return ResourceManager.GetString("ButtonSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check newer version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonVersionCheckToolTip {
            get {
                return ResourceManager.GetString("ButtonVersionCheckToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download the latest DLL at startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckDownloadAtStartup {
            get {
                return ResourceManager.GetString("CheckDownloadAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search the DLL on startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckSearchAtStartup {
            get {
                return ResourceManager.GetString("CheckSearchAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColEdit {
            get {
                return ResourceManager.GetString("ColEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColEnable {
            get {
                return ResourceManager.GetString("ColEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColPath {
            get {
                return ResourceManager.GetString("ColPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColReplace {
            get {
                return ResourceManager.GetString("ColReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColVersion {
            get {
                return ResourceManager.GetString("ColVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Global Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupGlobalHeader {
            get {
                return ResourceManager.GetString("GroupGlobalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupIgnoreHeader {
            get {
                return ResourceManager.GetString("GroupIgnoreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupTargetHeader {
            get {
                return ResourceManager.GetString("GroupTargetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking for {0}. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCheckingFor {
            get {
                return ResourceManager.GetString("MsgCheckingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dll not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDllNotFound {
            get {
                return ResourceManager.GetString("MsgDllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Download completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDownloadCompleted {
            get {
                return ResourceManager.GetString("MsgDownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDownloading {
            get {
                return ResourceManager.GetString("MsgDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download is not necessary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgDownloadNotNecessary {
            get {
                return ResourceManager.GetString("MsgDownloadNotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error : An error occurred while downloading {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorDownload {
            get {
                return ResourceManager.GetString("MsgErrorDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error : An error occurred while replase. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorReplace {
            get {
                return ResourceManager.GetString("MsgErrorReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error : An error occurred while searching {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorSearch {
            get {
                return ResourceManager.GetString("MsgErrorSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error : An error occurred while version check {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorVersionCheck {
            get {
                return ResourceManager.GetString("MsgErrorVersionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please execute after downloading the DLL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgExecuteAfterDownload {
            get {
                return ResourceManager.GetString("MsgExecuteAfterDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found {0} DLLs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgFoundDll {
            get {
                return ResourceManager.GetString("MsgFoundDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now checking version for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNowCheckingVersion {
            get {
                return ResourceManager.GetString("MsgNowCheckingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReplace {
            get {
                return ResourceManager.GetString("MsgReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} dlls has been replaced. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgReplaced {
            get {
                return ResourceManager.GetString("MsgReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   required version up for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgRequiredVersion {
            get {
                return ResourceManager.GetString("MsgRequiredVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the target path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSpecifyTargetPath {
            get {
                return ResourceManager.GetString("MsgSpecifyTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version up for {0}. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgVersionUpFor {
            get {
                return ResourceManager.GetString("MsgVersionUpFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version up is not necessary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgVersionupNotNecessary {
            get {
                return ResourceManager.GetString("MsgVersionupNotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgWarning {
            get {
                return ResourceManager.GetString("MsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified XPath does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgXPathNotExist {
            get {
                return ResourceManager.GetString("MsgXPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabAboutHeader {
            get {
                return ResourceManager.GetString("TabAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabMainHeader {
            get {
                return ResourceManager.GetString("TabMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabSettingsHeader {
            get {
                return ResourceManager.GetString("TabSettingsHeader", resourceCulture);
            }
        }
    }
}
